---
- name: Install and configure nginx for static website hosting
  hosts: all
  become: true

  tasks:
    - name: Install apache
      apt:
        name: httpd # this is name of apache service
        state: latest

    - name: Start Service #starting the service
      apt:
        name: httpd
        state: present
